---
# NOTE: deprecating the KDE role. Was only using it becase of kiosk mocde, which
# turns out to be poorly documented/supported. Switching to Gnome/dconf
# restrictions.
- name: Include task list appropriate for OS family (Debian/RedHat)
  include: "{{ ansible_os_family }}.yml"  

- name: Create sddm configuration (which enables autologin)
  template:
    src: sddm.conf.j2
    dest: /etc/sddm.conf
    owner: root
    group: root
    mode: 0444

#- name: Install desktop programs
#  include: programs.yml