---
# KDE for CentoS 8.1 needs the EPEL repository. But note there are broken dependencies.
- name: Add EPEL repository
  dnf:
    name: epel-release
    state: latest
  notify: Enable EPEL testing

- name: Install KDE
  dnf:
    name: "@KDE Plasma Workspaces"
    state: latest
    update_cache: yes
