---
  system_hostname: SNL # Edit to suit you

# Firewall settings
# Note the ufw role leaves SSH open by default
ufw_open_ports:
  https: 443 # note the key here ("https") isn't used elsewhere, just the port value ("443")

# Time zone
server_timezone: Europe/London

