---
# Edit the following to suit you
server_timezone: Europe/London # For acceptable entries here, see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
snl_user: snl                  # This is the name of the user that logs in automatically

# Firewall settings
# Note the ufw role leaves SSH open by default
ufw_open_ports:
  https: 443 # note the key here ("https") isn't used elsewhere, just the port value ("443")
