#!/usr/bin/env ansible-playbook
---
# See README.md for installation & guidance
- hosts: all
  become: true

  # The main config file should not be edited
  vars_files:
    - default.config.yml

  # End users of this playbook can amend the contents of config.yml to suit their requirements.
  # The config.yml file could also override settings in default.config.yml.
  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags:
        - always

  # Simple tasks that don't merit a role
  tasks:
    - name: Set time zone
      timezone:
        name: "{{ server_timezone }}"
      tags:
        - init

  roles:
    # Security, including external hardening roles
    - role: devsec.hardening.os_hardening
      tags:
        - security
    - role: devsec.hardening.ssh_hardening
      vars:
        sftp_enabled: true # Ansible prefers to use SFTP to copy files
        sftp_chroot: false
      tags:
        - security
    - role: selinux
      tags: security

    - role: packages
      tags:
        - init
    - role: name
      tags:
        - init
    - role: user
      tags:
        - init
    - role: gnome
      tags:
        - desktop
#    - role: proxy
#      tags:
#        - security
#        - proxy
#    - role: dev-sec.os-hardening
#      tags:
#        - security
#    - role: dev-sec.ssh-hardening
#      vars:
#        sftp_enabled: true
#      tags:
#        - security
