#!/usr/bin/env ansible-playbook
---
# See README.md for installation & guidance
- hosts: all
  become: true

  # The main config file should not be edited
  vars_files:
    - default.config.yml

  # End users of this playbook can amend the contents of config.yml to suit their requirements.
  # The config.yml file could also override settings in default.config.yml.
  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags:
        - always

  # Simple tasks that don't merit a role
  tasks:
    - name: Set time zone
      timezone:
        name: "{{ server_timezone }}"
      tags: [timezone, init]

  roles:
    # Security, including external hardening roles
    - role: dev-sec.os-hardening
      vars:
        os_filesystem_whitelist: squashfs # Needed for Snaps
      tags: [devsecos, security]
    - role: dev-sec.ssh-hardening
      vars:
        sftp_enabled: true # Ansible prefers to use SFTP to copy files
        sftp_chroot: false
      tags: [devsecssh, security]
    - role: selinux
      tags: [selinux, security]
    - role: firewall
      tags: [firewall, security]

    - role: name
      tags: [name, init]
    - role: network
      tags: [network, init]
    - role: packages
      tags: [packages, init]
    - role: user
      tags: [user, init]
    - role: gnome
      tags: [gnome, desktop]
    # dconf is used to lock down the desktop
    - role: dconf
      tags: [dconf, desktop]
    - role: gui-packages
      tags: [gui-packages, desktop]
    - role: proxy
      tags: [proxy, security]