- name: Give passwordless sudo to the 'sudo' group (validate with visudo program)
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: /sbin/visudo -cf %s
