- name: Give passwordless sudo to the 'wheel' group (validate with visudo program)
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: /sbin/visudo -cf %s
