---
- name: Start firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes

- name: Start ufw
  ansible.builtin.service:
    name: ufw
    state: started
    enabled: yes
