---
# Note: fzf needs perl (and git for the installation)
# This is the one time we update the cache (so must use apt rather than package)
- name: Install preferred packages
  apt:
    name:
      - fzf            # Fuzzy find - very useful: https://github.com/junegunn/fzf
      - htop           # Superior to top: https://github.com/htop-dev/htop
      - micro          # Great text editor: https://github.com/zyedidia/micro
      - mlocate        # File finder: https://pagure.io/mlocate
      - python3        # Keeps Python up to date
      - python3-pip    # Keeps Pip up to date
      - python3-psutil # Required, to Ansible manage dconf
      - tmux           # "terminal multiplexer": https://github.com/tmux/tmux
    state: latest
    update_cache: yes

- name: Populate service facts
  ansible.builtin.service_facts:
  changed_when: false

# hv_kvp_daemon isn't needed (usually) and causes a delay on VM boot
- name: Disable Hyper-V Key Value Pair daemon
  service:
    name: hv-kvp-daemon
    enabled: no
    state: stopped
  when: ansible_facts.services['hv-kvp-daemon.service'] is defined