---
# The proxy will be for local access only, so no firewall configuration required
- name: Include task list appropriate for OS family (Debian/RedHat)
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"  

- name: Copy config file
  ansible.builtin.template:
    src: privoxy.config.j2
    dest: /etc/privoxy/config
    owner: root
    group: root
    mode: 0644

- name: Copy Adblock Plus to Privoxy conversion script
  ansible.builtin.copy:
    src: abp2privoxy.sh
    dest: /usr/local/bin/abp2privoxy.sh
    owner: root
    group: root
    mode: 0700
  notify: Run abp2privoxy

- name: Create daily abp2privoxy cron job
  ansible.builtin.copy:
    src: abp2privoxy.cron
    dest: /etc/cron.daily/abp2privoxy
    owner: root
    group: root
    mode: 0755
  
- name: Enable privoxy
  ansible.builtin.service:
    name: privoxy
    enabled: yes
    state: started

- name: Configure environment-wide proxy
  ansible.builtin.lineinfile:
    path: /etc/environment
    regex: "^{{ item }}="
    line: "{{ item }}=http://127.0.0.1:8118"
  loop:
    - http_proxy
    - https_proxy

- name: Disable proxy for local addresses
  ansible.builtin.lineinfile:
    path: /etc/environment
    regex: "^no_proxy="
    line: no_proxy=localhost,127.0.0.1
