---
- name: Include task list appropriate for OS family (Debian/RedHat)
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"  

- name: Create Firefox policies directory
  ansible.builtin.file:
    path: /etc/firefox/policies
    state: directory
    owner: root
    group: root
    mode: 0755

# Firefox polices documented here: https://github.com/mozilla/policy-templates
- name: Install central Firefox policy
  ansible.builtin.template:
    src: firefox.policies.json.j2
    dest: /etc/firefox/policies/policies.json
    owner: root
    group: root
    mode: 0644
  when: firefox_install
