---
# Some Red Hat/AlmaLinux packages are only available as snaps, so we have to
# add the EPEL repo and install snapd to use them.
- name: Install EPEL repository
  ansible.builtin.dnf:
    name: "epel-release"
    state: latest

- name: Install Snap
  ansible.builtin.dnf:
    name: snapd
    state: latest
  register: snapd_installed

# TODO: Squashfs module is not installed. Fix?
# - name: Load squashfs kernel module
#   command: modprobe squashfs
#   when: snapd_installed is changed

- name: Enable snapd socket
  ansible.builtin.systemd:
    name: snapd
    enabled: yes
    state: started

- name: Download Tux Paint RPM
  ansible.builtin.get_url:
    url: http://z1.plala.jp/tuxpaint/el9/repo/tuxpaint-release-9-1.el9.noarch.rpm
    dest: /tmp/tuxpaint-release-9-1.el9.noarch.rpm
    checksum: sha256:d14807093ede49f87f4bc4c96c983d0f74e754891b086133f61d47659b127b4f
    mode: "0644"

# - name: Download SDL_image library (needed for Tux Paint)
#   get_url:
#     url: http://downloads.sourceforge.net/project/tuxpaint/prepackaged-libraries/rhel8/SDL_image-1.2.12-11.el8.x86_64.rpm
#     dest: /tmp/SDL_image-1.2.12-11.el8.x86_64.rpm
#     checksum: sha1:7e9007f3ac732a5586871b4e583b7182811951f2

# - name: Download SDL_mixer library (needed for Tux Paint)
#   get_url:
#     url: http://downloads.sourceforge.net/project/tuxpaint/prepackaged-libraries/rhel8/SDL_mixer-1.2.12-4.el8.x86_64.rpm
#     dest: /tmp/SDL_mixer-1.2.12-4.el8.x86_64.rpm
#     checksum: sha1:bde4dbe3173a450116093a22ba45a11b4e201e38

# - name: Download SDL_ttf library (needed for Tux Paint)
#   get_url:
#     url: http://downloads.sourceforge.net/project/tuxpaint/prepackaged-libraries/rhel8/SDL_ttf-2.0.11-6.el8.x86_64.rpm
#     dest: /tmp/SDL_ttf-2.0.11-6.el8.x86_64.rpm
#     checksum: sha1:abf42304da4ed1bbc953d41b92c418856619bafd

# - name: Download SDL_Pango library (needed for Tux Paint)
#   get_url:
#     url: http://downloads.sourceforge.net/project/tuxpaint/prepackaged-libraries/rhel8/SDL_Pango-0.1.2-21.el8.x86_64.rpm
#     dest: /tmp/SDL_Pango-0.1.2-21.el8.x86_64.rpm
#     checksum: sha1:2e823b261c3116efc359eeaf8c86999ff3084244

- name: Install Tux Paint packages
  ansible.builtin.dnf:
    name: /tmp/{{ item }}
    disable_gpg_check: yes
    state: present
  loop:
    # - SDL_image-1.2.12-11.el8.x86_64.rpm
    # - SDL_mixer-1.2.12-4.el8.x86_64.rpm
    # - SDL_ttf-2.0.11-6.el8.x86_64.rpm
    # - SDL_Pango-0.1.2-21.el8.x86_64.rpm
    - tuxpaint-release-9-1.el9.noarch.rpm

# TODO: Snapd isn't working due to suqashfs issue. Fix?
# - name: Install GUI snap packages (slow process!)
#   community.general.snap:
#     name:
#       - gcompris

- name: Install GUI packages
  ansible.builtin.package:
    name:
      - ktuberling
    state: latest

- name: Install Firefox
  ansible.builtin.dnf:
    name: firefox
    state: latest
  when: firefox_install

- name: Uninstall Firefox
  ansible.builtin.dnf:
    name: firefox
    state: absent
  when: not firefox_install
