---
- name: Include task list appropriate for OS family (Debian/RedHat)
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml" 

- name: Override DHCP DNS servers (Debian)
  ansible.builtin.lineinfile:
    path: /etc/dhcp/dhclient.conf
    regex: "^supersede domain-name-servers"
    line: "supersede domain-name-servers {{ dns_servers | join(',') }};"
  when: ansible_os_family == "Debian"

# from /etc/sysconfig/network-scripts/readme-ifcfg-rh.txt:
# NetworkManager stores new network profiles in keyfile format in the
# /etc/NetworkManager/system-connections/ directory.
# 
# Previously, NetworkManager stored network profiles in ifcfg format
# in this directory (/etc/sysconfig/network-scripts/). However, the ifcfg
# format is deprecated. By default, NetworkManager no longer creates
# new profiles in this format.
#
# TODO: Implement this for RedHat based Linuxes based on this task.
# - name: Override DHCP DNS servers (RedHat)
#   ansible.builtin.blockinfile:
#     path: "/etc/NetworkManager/system-connections/enp0s3.nmconnection"
#     block: |
#       DNS1={{ dns_servers[1] }}
#       DNS2={{ dns_servers[2] }}
#   when: ansible_os_family == "RedHat"
