---
## ESSENTIALS

- name: Install ufw
  ansible.builtin.package:
    name: ufw
    state: latest
  notify: Start ufw

- name: Allow SSH through firewall
  ansible.builtin.ufw:
    rule: allow
    name: OpenSSH

- name: Enable ufw
  ansible.builtin.ufw:
    state: enabled

## ALL OTHER RULES

# - name: Allow HTTP and HTTPS through firewall
#   ansible.builtin.ufw:
#     rule: allow
#     port: "{{ item }}"
#   loop: [http, https]
