- name: Include task list appropriate for OS family (Debian/RedHat)
  ansible.builtin.include: "{{ ansible_os_family }}.yml"  

- name: Enable GDM's automatic login feature
  community.general.ini_file:
    path: "/etc/gdm{{ (ansible_os_family == 'RedHat') | ternary('', '3') }}/custom.conf"
    section: daemon
    option: AutomaticLoginEnable
    value: "True"
    no_extra_spaces: yes

- name: Suppress gnome-initial-setup application
  community.general.ini_file:
    path: "/etc/gdm{{ (ansible_os_family == 'RedHat') | ternary('', '3') }}/custom.conf"
    section: daemon
    option: InitialSetupEnable
    value: "False"
    no_extra_spaces: yes

- name: Enable automatic login for SNL user
  community.general.ini_file:
    path: "/etc/gdm{{ (ansible_os_family == 'RedHat') | ternary('', '3') }}/custom.conf"
    section: daemon
    option: AutomaticLogin
    value: "{{ snl_user }}"
    no_extra_spaces: yes

- name: Disable Gnome Initial Setup screen
  community.general.ini_file:
    path: /etc/xdg/autostart/gnome-initial-setup-first-login.desktop
    section: Desktop Entry
    option: X-GNOME-Autostart-enabled
    value: "false"
    owner: root
    group: root
    mode: 0644
    no_extra_spaces: yes

# The applications listed may or may not be installed (depending on distro)
- name: Hide unnecessary application icons
  community.general.ini_file:
    path: "/usr/share/applications/{{ item }}"
    section: "Desktop Entry"
    option: NoDisplay
    value: "true"
    no_extra_spaces: yes
  loop:
    - byobu.desktop
    - htop.desktop
    - info.desktop
    - vim.desktop

# Not strictly Gnome-related, but no need for a separate role just for this
- name: Create /etc/X11/xorg.conf.d directory
  ansible.builtin.file:
    path: /etc/X11/xorg.conf.d
    state: directory
    owner: root
    group: root
    mode: 0755
- name: Disable switching virtual terminals
  ansible.builtin.copy:
    src: 10-xorg.conf
    dest: /etc/X11/xorg.conf.d/10-xorg.conf
    owner: root
    group: root
    mode: 0644
