---
- name: Install GUI packages
  apt:
    name:
      - firefox
      - gcompris-qt
      - gcompris-qt-data
      - ktuberling
      - tuxpaint
      - tuxpaint-data
    state: latest
    update_cache: yes
