---
- name: Install GUI packages
  apt:
    name:
      - gcompris-qt
      - gcompris-qt-data
      - ktuberling
      - tuxpaint
      - tuxpaint-data
    state: latest
    update_cache: yes

- name: Install Firefox
  apt:
    name: firefox
    state: latest
  when: firefox_install == true

- name: Uninstall Firefox
  apt:
    name: firefox
    state: absent
  when: firefox_install != true