---
# Some Red Hat/Oracle Linux packages are only available as snaps
- name: Install Snap
  dnf:
    name: snapd
    state: latest
  notify: Load squashfs kernel module

- name: Enable snapd socket
  systemd:
    name: snapd
    enabled: yes
    state: started

- name: Download Tux Paint RPM
  get_url:
    url: http://downloads.sourceforge.net/project/tuxpaint/tuxpaint/0.9.26/tuxpaint-0.9.26-1.el8.x86_64.rpm
    dest: /tmp/tuxpaint-0.9.26-1.el8.x86_64.rpm
    checksum: sha1:f06fbb916cf18116ac0a19fde549650d2fc6390d

- name: Download SDL_image library (needed for Tux Paint)
  get_url:
    url: http://downloads.sourceforge.net/project/tuxpaint/prepackaged-libraries/rhel8/SDL_image-1.2.12-11.el8.x86_64.rpm
    dest: /tmp/SDL_image-1.2.12-11.el8.x86_64.rpm
    checksum: sha1:7e9007f3ac732a5586871b4e583b7182811951f2

- name: Download SDL_mixer library (needed for Tux Paint)
  get_url:
    url: http://downloads.sourceforge.net/project/tuxpaint/prepackaged-libraries/rhel8/SDL_mixer-1.2.12-4.el8.x86_64.rpm
    dest: /tmp/SDL_mixer-1.2.12-4.el8.x86_64.rpm
    checksum: sha1:bde4dbe3173a450116093a22ba45a11b4e201e38

- name: Download SDL_ttf library (needed for Tux Paint)
  get_url:
    url: http://downloads.sourceforge.net/project/tuxpaint/prepackaged-libraries/rhel8/SDL_ttf-2.0.11-6.el8.x86_64.rpm
    dest: /tmp/SDL_ttf-2.0.11-6.el8.x86_64.rpm
    checksum: sha1:abf42304da4ed1bbc953d41b92c418856619bafd

- name: Download SDL_Pango library (needed for Tux Paint)
  get_url:
    url: http://downloads.sourceforge.net/project/tuxpaint/prepackaged-libraries/rhel8/SDL_Pango-0.1.2-21.el8.x86_64.rpm
    dest: /tmp/SDL_Pango-0.1.2-21.el8.x86_64.rpm
    checksum: sha1:2e823b261c3116efc359eeaf8c86999ff3084244

- name: Install Tux Paint packages
  dnf:
    name: /tmp/{{ item }}
    disable_gpg_check: yes
    state: present
  loop:
    - SDL_image-1.2.12-11.el8.x86_64.rpm
    - SDL_mixer-1.2.12-4.el8.x86_64.rpm
    - SDL_ttf-2.0.11-6.el8.x86_64.rpm
    - SDL_Pango-0.1.2-21.el8.x86_64.rpm
    - tuxpaint-0.9.26-1.el8.x86_64.rpm

- name: Install GUI snap packages (slow process!)
  community.general.snap:
    name:
      - gcompris
      - ktuberling

- name: Install Firefox
  dnf:
    name: firefox
    state: latest
  when: firefox_install == true

- name: Uninstall Firefox
  dnf:
    name: firefox
    state: absent
  when: firefox_install != true