---
- name: Install default Plymouth splash screen
  ansible.builtin.apt:
    name: plymouth-theme-ubuntu-logo
    state: latest
  notify:
    - "Plymouth tasks"
  when: ansible_os_family == "Debian"
