---
- name: Run dconf update
  ansible.builtin.command: dconf update
  listen: Update dconf databases

- name: Set permissions on local database
  ansible.builtin.file:
    path: /etc/dconf/db/local
    mode: 0644
  listen: Update dconf databases
